### ISSUE TITLE
Investigate handling for mini.nvim 

### ISSUE THREAD

**Issue by codicocodes** [codicocodes/dotfyle#10]

**Comment by codicocodes** [comment]
mini.nvim is now tracked!

**Comment by echasnovski** [comment]
@codicocodes, the main reason I ask is because there is already a new one missing in [SUBMITTED-PLUGINS.md](https://github.com/codicocodes/dotfyle/blob/8ead1eb1059b331036475fcb73e54f3df978c571/SUBMITTED-PLUGINS.md).
