### ISSUE TITLE
lua-specific heuristic

### ISSUE THREAD

**Issue by napisani** [codicocodes/dotfyle#123]
Hi There, 

I authored a neovim remote plugin called [`napisani/nvim-dadbod-bg` ](https://github.com/napisani/nvim-dadbod-bg) using official https://github.com/neovim/go-client library.

I was hoping to register this plugin on dotfyle.com, but since the plugin is not implemented in lua it fails validation when I attempt to submit it.

I was wondering if that validation could be loosened or if there is an exception you would be willing to make for this plugin? 

If not, I completely understand - lua project validation is a perfectly reasonable heuristic validation mechanism imo.

**Comment by codicocodes** [comment]
Added the plugin here: https://dotfyle.com/plugins/napisani/nvim-dadbod-bg

I use it as a heuristic to stop spam repositories from being uploaded.

**Comment by napisani** [comment]
Thank you!!
