### ISSUE TITLE
"Repository name is required" when submitting plugin

### ISSUE THREAD

**Issue by WhyNotHugo** [codicocodes/dotfyle#135]
Hi there. I'm trying to submit [`lsp_lines.nvim`](https://git.sr.ht/~whynothugo/lsp_lines.nvim) using the form at https://dotfyle.com/neovim/plugins/add.

I get an error indicating `Repository name is required`. I'm not sure what this means.

I'm providing the URL `https://git.sr.ht/~whynothugo/lsp_lines.nvim` which seems to be working fine right now (confirmed by running `git clone`). Do I need some special syntax? I'm not sure what this means by `Repository name`.

**Comment by codicocodes** [comment]
Only GitHub repositories are supported.

The format to provide is: owner/repository -> separated by forward slash
