### ISSUE TITLE
Config repo not showing up in 'add new neovim config' wizard

### ISSUE THREAD

**Issue by noqqe** [codicocodes/dotfyle#18]
Hi,

My neovim config repo is not showing up in the add config dialog of the website.

I doublechecked my repo is public, and it is: [vim](https://github.com/noqqe/vim)

![Screen Shot 2023-04-14 at 10 26 17](https://user-images.githubusercontent.com/203902/231988445-f06d4160-ae79-4950-93a3-39d399c93014.png)

Any idea what am I doing wrong?

**Comment by codicocodes** [comment]
Thanks for reporting! 

It's because I filter out repositories with the same name as tracked plugins. And there happens to be a plugin named "vim". I added a special case for vim, so you should be able to add your config!
