### ISSUE TITLE
Improve project documentation and setup for new contributors

### ISSUE THREAD

**Issue by francis-robert** [codicocodes/dotfyle#19]
### Problem

As a potential contributor, it can be challenging to figure out how to get started with the project due to the lack of documentation and setup guidelines. For example, I hit a wall running `npm run build`. The project has a lot of potential, and having more contributors onboard would be beneficial.

### Proposed Solution

To make it easier for new contributors to get started, I suggest creating and updating the following project files:

1. **README.md** - Provide a comprehensive overview of the project, including its purpose, features, installation steps, usage, and any other relevant information.

2. **CONTRIBUTING.md** - Create a clear guide on how to contribute to the project. This should include information on submitting issues, pull requests, coding conventions, testing, and any other project-specific contribution guidelines.
2.5. Alternatively, issue templates could serve the same purpose but be slightly more streamlined.

4. **.env.template** - Include a sample environment file to help new contributors set up their local environment. This should contain all necessary environment variables with placeholder values and descriptions

**Comment by codicocodes** [comment]
Thanks to @creativenull we now have a [CONTRIBUTING.md](https://github.com/codicocodes/dotfyle/blob/dev/CONTRIBUTING.md) with a guide on setting up the dev environment. https://github.com/codicocodes/dotfyle/pull/20

The README has also been updated to be more informative.

Both documents are works in progress that will continuously be improved.

Thank you for making the issue! I will close it for now, if you have any further ideas feel free to continue contributing!
