### ISSUE TITLE
cannot add config repos in GitHub Orgs 

### ISSUE THREAD

**Issue by practicalli-john** [codicocodes/dotfyle#22]
My config is [in a GitHub Org](github.com/practicalli/), along with books and other repositories to help use Neovim

When adding a config, the website only shows repositories from the account, so my config is not found.

Consider either of the following
- option to paste in a GitHub repository URL
- option to search through a selected GitHub Org

Thank you

**Comment by codicocodes** [comment]
Thank you for making the issue. Sorry for the inconvenience.

At the moment I don't plan to add either of these options. If you want to get around this, I suggest forking the repository to your personal account.

**Comment by practicalli-john** [comment]
Okay thanks for letting me know.  I will leave the site for now but wish you success
