### ISSUE TITLE
Redirect directly to config page when sync comples

### ISSUE THREAD

**Issue by codicocodes** [codicocodes/dotfyle#36]
Currently you end up on this page

![image](https://github.com/codicocodes/dotfyle/assets/76068197/d1d789d1-d7bb-4945-aad7-edfb92ecb5af)

Instead you should be redirected directly to /{user}/{config-slug}

![image](https://github.com/codicocodes/dotfyle/assets/76068197/b221818d-54c7-4515-ad84-e4c3efba9fcc)

**Comment by JayK1524** [comment]
I would like to work on this issue. Please guide me, how can I resolve this.

**Comment by codicocodes** [comment]
Follow https://github.com/codicocodes/dotfyle/blob/main/CONTRIBUTING.md to get started,

After setup, authenticate with GitHub and navigate to `http://localhost:5173/add` to go through the feature which adds a new config.

Let me know if you have more questions after completing the setup and syncing your first config!
