### ISSUE TITLE
Support rss feed for this-week-in-neovim

### ISSUE THREAD

**Issue by codicocodes** [codicocodes/dotfyle#37]
[this-week-in-neovim.org](https://www.this-week-in-neovim.org)  provided an rss feed, [dotfyle.com/this-week-in-neovim](https://dotfyle.com/this-week-in-neovim) does not currently support an rss feed for consuming TWiN. We should add support for this once we start curating new issues of TWiN.

**Comment by farzadmf** [comment]
I think it may not be a bad idea to have RSS feeds for other things as well and not just TWIN section

**Comment by codicocodes** [comment]
If someone wants to pick up this issue and make a simple RSS feed for the TWiN contents, please do so! I'll help evalaute it and iterate on it.

At the moment I'm prioritizing making it easier to curate the contents, because without good TWiN content the rss feed is not as important.

**Comment by codicocodes** [comment]
Actually, maybe I will get something simple running for this... if not feel free to pick it up

**Comment by codicocodes** [comment]
Added an rss feed at https://dotfyle.com/this-week-in-neovim/rss.xml

**Comment by codicocodes** [comment]
Let me know if you have any feedback on the feed please!

**Comment by farzadmf** [comment]
That's great @codicocodes ; thank you for the quick action.

First impression: really nice; will update if I can think of some feedback

**Comment by codicocodes** [comment]
Additionally there is now a RSS feed for new plugins at: https://dotfyle.com/neovim/plugins/rss.xml
