### ISSUE TITLE
[Request] Light theme

### ISSUE THREAD

**Issue by Massolari** [codicocodes/dotfyle#44]
I have astigmatism and find it easier to read on a light theme (light background with darker fonts).

Could a toggle be implemented so we may switch from the dark to the light theme?

**Comment by codicocodes** [comment]
Thank you for the feature request!

I would love to support a theme toggle with light theme, but realistically do not have the time to implement it right now.

If someone reads this, it would be great if someone can get started on this in a PR, I would be happy to collaborate to get it to completion. 

Preferably if someone has experience setting up tailwind themes in a good way.
