### ISSUE TITLE
Consider making TWiN RSS feed autodiscoverable

### ISSUE THREAD

**Issue by metiulekm** [codicocodes/dotfyle#51]
See <https://dri.es/rss-auto-discovery>. This would make it slightly easier to find the RSS feed, especially if someone is linked to the issue page directly, which only has a little RSS link in the footer.

(I'd probably try this myself, but preparing the dev environment was too complex for me :/)

**Comment by codicocodes** [comment]
You can probably skip most of the steps for settings up just RSS, you don't need to seed data to test it

**Comment by codicocodes** [comment]
I added the link tag for this, @metiulekm please confirm if it's working or not.

**Comment by metiulekm** [comment]
Works perfectly for me. By the way, thank you for working on TWiN :)
