### ISSUE TITLE
Add init.fnl as accepted init file

### ISSUE THREAD

**Issue by LordMZTE** [codicocodes/dotfyle#54]
Dotfyle currently won't let me specify my root config file because of my sophisticated Neovim config build system where my config consists of a native part in Zig and interpreted parts in Fennel. In order to accommodate this as well as even more exotic setups, it'd be great if any file in the dotfiles repo could be selected.

For my neovim config, see [this directory in my dotfiles](https://mzte.de/git/LordMZTE/dotfiles/src/branch/master/mzte-nv) ([github mirror](https://github.com/LordMZTE/dotfiles/tree/master/mzte-nv)).

In my case, I'd consider the best candidate for a "root init file" to be [this file](https://mzte.de/git/LordMZTE/dotfiles/src/branch/master/mzte-nv/src/main.zig), however I'm just met with this unhelpful dialog:
![image](https://github.com/codicocodes/dotfyle/assets/28735087/28105d53-351f-4b85-b0ee-61723ee9b6a3)

**Comment by LordMZTE** [comment]
Just read about dotfyle analyzing configs for metadata, my config is obviously a lost cause here, but it'd still be neat if I could add it.

**Comment by codicocodes** [comment]
At the moment I validate that the init file is `init.vim` or `init.lua` to limit people from uploading repositories that are not actually Neovim configurations. I can imagine people just adding garbage repositories that need to be moderated (which I would like to minimize).

I appreciate your use case, and will think about it. If you have ideas taking these concerns in mind as well please let me know.

**Comment by LordMZTE** [comment]
My config would theoretically work if we also allowed `init.fnl` (which I think is actually somewhat common place). This file however isn't particularly interesting on my setup, so maybe we check that either `init.fnl`, `init.vim` or `init.lua` is present and then allow to user to pick an arbitrary file?

**Comment by codicocodes** [comment]
`init.fnl` is a good point, I will add support for it.

**Comment by codicocodes** [comment]
Added support for `init.fnl` - which makes it possible to sync your config.

Your plugins and metadata are still not picked up properly, but at least the config can be uploaded.

![image](https://github.com/codicocodes/dotfyle/assets/76068197/473d5b5a-ae3e-48d8-84bb-6ebabdffbd63)

We have a project in the works that might be helpful here https://github.com/creativenull/dotfyle-metadata.nvim - but it's not supported in dotfyle yet.

**Comment by LordMZTE** [comment]
Thanks!
