### ISSUE TITLE
Slack embeds the same for main page and repo view

### ISSUE THREAD

**Issue by technicalpickles** [codicocodes/dotfyle#57]
I shared https://dotfyle.com/ and https://dotfyle.com/ to https://dotfyle.com/technicalpickles/pickled-nvim to one of the Slacks I am in, and was surprised they render the same:

![CleanShot 2023-07-29 at 12 31 54](https://github.com/codicocodes/dotfyle/assets/159/d761406b-4690-436d-909c-6f38dba9791b)

It took a bit to find, but this is how Slack decides what to display: https://api.slack.com/reference/messaging/link-unfurling#classic_unfurl ie opengraph or twitter card metadata.

I found this which talks about how to implement opengraph: https://whitep4nth3r.com/blog/level-up-your-link-previews-in-slack/

**Comment by codicocodes** [comment]
Thanks for the suggestion and for the research as well! I will add this to my todo list. It would be a really nice improvement.

**Comment by codicocodes** [comment]
This is now resolved thank you for making the issue. LMK if it doesn't work in slack  (remember to bust the cache).

I might make some changes to the text but happy with this for now.

![image](https://github.com/codicocodes/dotfyle/assets/76068197/a13706b3-e059-4f37-b456-d09dac37deb3)

**Comment by technicalpickles** [comment]
Looks great! The main convention I've seen is, for user pages, to use their avatar for the image, in case that is helpful.

**Comment by codicocodes** [comment]
Hmm, I did not think that would work, but maybe it would. I will try it out later!
