### ISSUE TITLE
LOC count

### ISSUE THREAD

**Issue by paulfrische** [codicocodes/dotfyle#60]
I think a lines of code count would be nice to have. I doesn't really matter but it can give you a feeling for the complexity of a config. 
Have a great day!

**Comment by justinmk** [comment]
Could be useful. But if https://github.com/neovim/packspec or something similar gains traction, then "dependency size" would be another metric worth surfacing.

**Comment by codicocodes** [comment]
LOC is a good idea. I was considering saving size in bytes as well, because it is returned by the GitHub API. LOC might be more immediately understandable. 

I've definitely got my eye on https://github.com/neovim/packspec, I think we could use it in several ways.

**Comment by codicocodes** [comment]
Added LOC to configs, I was recently rewriting my config and wish I had this feature then as I was looking through configs for references and did not want to bother with complex configs. Great suggestions!
