### ISSUE TITLE
styles: input field accessibility

### ISSUE THREAD

**Issue by chamanbravo** [codicocodes/dotfyle#80]
![image](https://github.com/codicocodes/dotfyle/assets/76839908/c0f47be3-f24c-4fba-8c96-8515987f6c3c)
text not visible in filter input field

![image](https://github.com/codicocodes/dotfyle/assets/76839908/d298ad28-4b20-42ae-aae0-3211b5c95261)
two cross in input field

**Comment by codicocodes** [comment]
Thanks for the issue, I will try to prioritize this.

Some of the styling issues is likely related to recent theme changes and adding light mode.

**Comment by codicocodes** [comment]
This should now be resolved:

![image](https://github.com/codicocodes/dotfyle/assets/76068197/1cd344ee-b7f1-4459-96ff-add8285b6999)

![image](https://github.com/codicocodes/dotfyle/assets/76068197/65109028-14a1-4918-ad8e-0f90ec6153d9)
