### ISSUE TITLE
The color of modal component doesn't toggle with theme

### ISSUE THREAD

**Issue by neolooong** [codicocodes/dotfyle#95]
<img width="262" alt="example" src="https://github.com/codicocodes/dotfyle/assets/32055974/4007163b-416a-448d-a133-acdb6b9fc49c">

**Comment by codicocodes** [comment]
Thanks for the report!

Got a fix on the way

![image](https://github.com/codicocodes/dotfyle/assets/76068197/b3030f0b-5e8d-4058-9882-6129c226969e)
